### ISSUE TITLE
What software/hardware do you use on a daily basis?

### ISSUE THREAD

**Issue by mustafauysal** [danielbachhuber/ama#2]

**Comment by danielbachhuber** [comment]
Hardware:

* MacBook Pro (Retina, 13-inch, Mid 2014) with 3 GHz Intel Core i7 and 16 GB RAM
* Apple Thunderbolt display (probably 4 or 5 years old now)
* iPhone 5 SE
* [Audio-Technica ATH-M50xBL](https://www.amazon.com/Audio-Technica-ATH-M50xBL-Professional-Monitor-Headphones/dp/B00HVLUSGM/)

Software:

* [Things](https://culturedcode.com/things/)
* [iTerm 2](https://www.iterm2.com/) full screen
* Sublime Text 3 (see #1)
* [zsh](http://www.zsh.org/) with the [dannybachhuber](https://github.com/danielbachhuber/dotfiles/blob/master/oh-my-zsh-themes/dannybachhuber.zsh-theme) theme
* [shell aliases](https://github.com/danielbachhuber/dotfiles/blob/master/aliases)
* [Mailplane](http://mailplaneapp.com/), because I like my email in a desktop app and my Gmail in the browser.
* Usual suspects: Spotify, Slack, Chrome, Tweetbot, etc.

Web Services:

* [Capsule CRM](https://capsulecrm.com/)
* [Harvest](https://handbuiltco.harvestapp.com/)
* [Memberful](https://memberful.com/)
* Usual suspects: GitHub, Trello, Google Docs
