### ISSUE TITLE
What are your most and least favorite things about being a parent?

### ISSUE THREAD

**Issue by tnorthcutt** [danielbachhuber/ama#3]

**Comment by danielbachhuber** [comment]
I actually don't think about parenting in terms of "most and least favorite". It's one of the most rewarding things I've done in my life. I consider the two emotional extremes to be joy and effort.

Parenting is most joyful when I'm 100% in my kids' worlds. It's amazing how much of life I previously considered mundane is now really interesting again because I get to see it through their eyes. Even though I swim laps a couple times a week, I _love_ taking my kids to swim lessons because I get to experience what it's like to learn how to swim.

Parenting requires a ton of effort when things don't go the way I want them to. For instance, sometimes Ava has trouble staying in bed at night when she's not tired enough. When I say "trouble staying in bed", I mean she'll get out of bed, lie on the floor by the door, I'll go in and put her back to bed, and then she'll get out of bed again. It requires a ton of effort for me to suck it up and deal with it — gotta be done.

Obligatory kid photo:

![image](https://cloud.githubusercontent.com/assets/36432/22083835/8b184dee-dd82-11e6-9a7f-9fac97fbefd5.png)

**Comment by tnorthcutt** [comment]
> I consider the two emotional extremes to be joy and effort.

Very good way of putting it.
