### ISSUE TITLE
WordPress starter theme

### ISSUE THREAD

**Issue by phh** [danielbachhuber/ama#5]
When you start developing a new site for a client where do you start in terms of the theme?
Underscores? Are you using any .org themes? Are you buying premium themes? Do you have your own boilerplate to get started?

**Comment by danielbachhuber** [comment]
I don't use a standard starter theme, but I certainly reuse some of my code.

Rationale for the former: if the site isn't going to use some large percentage of the code in the starter theme, I'm better off spending 30 minutes setting up a new theme with exactly what I want, instead of fighting a bunch of code I don't want.

As far as reusable code goes, https://github.com/danielbachhuber/danielbachhuber-theme has a lot of it, specifically:

* https://github.com/danielbachhuber/danielbachhuber-theme/blob/master/Gruntfile.js for compiling SCSS
* https://github.com/danielbachhuber/danielbachhuber-theme/blob/master/functions.php#L57-L81 for a class autoloader
* https://github.com/danielbachhuber/danielbachhuber-theme/blob/master/functions.php#L104-L126 for a template part fetcher

More often than not, I'll also use [Foundation by Zurb](http://foundation.zurb.com/), which I really like.
